
on: push
name: build
jobs:
  checks:
    name: run
    runs-on: ubuntu-latest
    steps:
      - run:  |
               sudo apt update
               sudo apt install gcc-10 g++-10
      - uses: actions/checkout@v2
        with:
          ref: pk/re2

      - name: run
        uses: ngalaiko/bazel-action/2.0.0@master
        with:
          environment:
            CC: gcc-10
            CXX: g++-10
          args: build //...
