
on: push
name: build
jobs:
  checks:
    name: run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: pk/re2

      - name: run
        uses: ngalaiko/bazel-action/2.0.0@master
        with:
          env:
            CC: gcc-8
            CXX: g++-8
          args: build //...
